### ISSUE TITLE
Cant execute

### ISSUE THREAD

**Issue by fig-shimooka** [ezWheelSAS/swd-starter-kit-config#1]
I get an error when I run swd_left_4_commissioning.py.
Why?

The ezw-swd-left.service is running.

$ python3 swd_left_4_commissioning.py 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'commonapi.SmcService.NMT.v1_0_commonapi.ezw.smcservice.swd_left': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "swd_left_4_commissioning.py", line 178, in <module>
    main(sys.argv[1:])
  File "swd_left_4_commissioning.py", line 100, in main
    commissioning.create_dbus_clients(instance_id)
  File "/opt/ezw/commissioning/commissioning.py", line 196, in create_dbus_clients
    nmt_client = NMTDBusClient(instance_id)
  File "/opt/ezw/usr/lib/smcdbusclient/nmt.py", line 49, in __init__
    self.dbus_object = self.bus.get_object(
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name commonapi.SmcService.NMT.v1_0_commonapi.ezw.smcservice.swd_left was not provided by any .service files

● ezw-swd-left.service - EZW SWD LEFT SERVICE
    Loaded: loaded (/etc/systemd/system/ezw-swd-left.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-03-17 19:21:54 JST; 1h 38min ago
   Main PID: 880 (sce-swd-left.sh)
      Tasks: 8 (limit: 9243)
     Memory: 16.7M
     CGroup: /system.slice/ezw-swd-left.service
             ├─ 880 /bin/bash /opt/ezw/sbin/sce-swd-left.sh start
             ├─1075 /bin/bash /opt/ezw/sbin/sce-swd-left.sh start
             ├─1076 grep -E --line-buffered ;WARN;|;ERROR;
             └─1077 /opt/ezw/usr/bin/ezw-smc-service /opt/ezw/usr/etc/ezw-smc-core/swd_left_config.ini

Mar 17 19:21:54 x86 systemd[1]: Started EZW SWD LEFT SERVICE.
Mar 17 19:21:55 x86 sce-swd-left.sh[966]: loading ini variables ...
Mar 17 19:21:55 x86 sce-swd-left.sh[977]: [
Mar 17 19:21:55 x86 sce-swd-left.sh[987]: 
Mar 17 19:21:55 x86 sce-swd-left.sh[992]:   OK
Mar 17 19:21:55 x86 sce-swd-left.sh[995]: 
Mar 17 19:21:55 x86 sce-swd-left.sh[1003]: ]
Mar 17 19:21:55 x86 sce-swd-left.sh[1012]: Run on ROBOT With Role Master  : Starting

**Comment by GMezWheel** [comment]
Does the service of ezw-canopen is started ?

At minimal, the following systemctl service have to be started for commissioning:
```
> systemctl -a | grep ezw
ezw-dbus-user-session (optional if a dbus session already exists. eg graphical dbus session)
ezw-stack
ezw-canopen
ezw-swd-left
ezw-swd-right
````
